# -*- encoding: utf-8 -*-
#
# Copyright 2017 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

---
- name: Incluse OS-specific variables
  include_vars: '{{ ansible_os_family  }}.yml'

- name: Include RPM-based repo (when necessary)
  include_tasks: CentOS/rpm-based-repo.yml
  when: ansible_distribution == 'CentOS'

- name: Ensure blackbox-exporter is installed
  become: True
  package:
    name: '{{ prometheus_blackbox_exporter_package_name }}'

- name: Ensure configuration is installed
  become: True
  template:
    src: etc/prometheus/blackbox.yml.j2
    dest: '{{ prometheus_blackbox_exporter_config_path }}'
  notify: prometheus_blackbox_exporter-restart

- name: Ensure start-up configuration is set (RedHat)
  become: True
  lineinfile:
    path: /etc/default/blackbox_exporter
    regexp: '^BLACKBOX_EXPORTER_OPTS='
    line: 'BLACKBOX_EXPORTER_OPTS="--{{ " --".join(prometheus_blackbox_exporter_opts) }}"'
  when: prometheus_blackbox_exporter_opts is defined and ansible_os_family == 'RedHat'
  notify: prometheus_blackbox_exporter-restart

- name: Ensure start-up configuration is set (FreeBSD)
  become: True
  lineinfile:
    path: /etc/rc.conf
    regexp: '^blackbox_exporter_args='
    line: 'blackbox_exporter_args="--{{ " --".join(prometheus_blackbox_exporter_opts) }}"'
  when: prometheus_blackbox_exporter_opts is defined and ansible_os_family == 'FreeBSD'
  notify: prometheus_blackbox_exporter-restart

- name: Ensure blackbox-exporter is started and enabled
  become: True
  service:
    name: '{{ prometheus_blackbox_exporter_service_name }}'
    state: started
    enabled: yes
